UNIMAS = read.csv("UNIMAS.csv")
UMT = read.csv("UMT.csv")
UMS = read.csv("UMS.csv")
UUM = read.csv("UUM.csv")
UM = read.csv("UM.csv")
USM = read.csv("USM.csv")
UTM = read.csv("UTM.csv")
UKM = read.csv("UKM.csv")
UMP = read.csv("UMP.csv")
UNIMAP = read.csv("UNIMAP.csv")
UMK = read.csv("UMK.csv")
UTHM = read.csv("UTHM.csv")

data = rbind(UM, USM, UTM, UKM, UNIMAS, UMT, UMS, UUM, UMP, UNIMAP, UMK, UTHM)
data = read.csv("dataset.csv")

data02 = read.csv("dataset02.csv")
  ##Faculty
FacUM = read.csv("UMfac.csv")
FacUSM = read.csv("USMfac.csv")
FacUKM = read.csv("UKMfac.csv")
FacUTM = read.csv("UTMfac.csv")
FacUUM = read.csv("UUMfac.csv")
FacUMS = read.csv("UMSfac.csv")
FacUMT = read.csv("UMTfac.csv")
FacUNIMAS = read.csv("UNIMASfac.csv")
FacUMP = read.csv("UMPfac.csv")
FacUNIMAP = read.csv("UNIMAPfac.csv")
FacUMK = read.csv("UMKfac.csv")
FacUTHM = read.csv("UTHMfac.csv")
FacUTEM = read.csv("UTEMfac.csv")
FacUPSI = read.csv("UPSIfac.csv")
FacUnisza = read.csv("UNISZAfac.csv")
FacUPNM = read.csv("UPNMfac.csv")

faculty = rbind(FacUM,FacUSM, FacUKM,FacUTM,FacUUM,FacUMS,FacUMT,FacUNIMAS,FacUMP,
                FacUNIMAP, FacUMK, FacUTHM, FacUTEM, FacUPSI, FacUnisza, FacUPNM)
